// <auto-generated />
namespace Db.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class unicode : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(unicode));
        
        string IMigrationMetadata.Id
        {
            get { return "201308191329242_unicode"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
