// <auto-generated />
namespace Db.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class PostTagColumFix : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostTagColumFix));
        
        string IMigrationMetadata.Id
        {
            get { return "201308190949263_PostTagColumFix"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
